---
  - name: install chromium
  hosts: localhost
  become: true
  tasks:
    - name: add ppa repository
      apt_repository:
        repo: 'ppa:canonical-chromium-builds/stage'
        state: present
      become: yes
      become_user: root
    - name: install chromium
      apt:
        name: chromium-browser
        state: present
      become: yes
      become_user: root